// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (
    id,
    name,
    key_hash,
    mode
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, name, key_hash, mode, is_revoked, last_used_at, created_at, revoked_at
`

type CreateAPIKeyParams struct {
	ID      string
	Name    string
	KeyHash string
	Mode    string
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ID,
		arg.Name,
		arg.KeyHash,
		arg.Mode,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyHash,
		&i.Mode,
		&i.IsRevoked,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, name, key_hash, mode, is_revoked, last_used_at, created_at, revoked_at
FROM api_keys
WHERE key_hash = $1
  AND is_revoked = FALSE
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyHash,
		&i.Mode,
		&i.IsRevoked,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, name, key_hash, mode, is_revoked, last_used_at, created_at, revoked_at
FROM api_keys
ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeys(ctx context.Context) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.KeyHash,
			&i.Mode,
			&i.IsRevoked,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE api_keys
SET is_revoked = TRUE,
    revoked_at = $1
WHERE id = $2
RETURNING id, name, key_hash, mode, is_revoked, last_used_at, created_at, revoked_at
`

type RevokeAPIKeyParams struct {
	RevokedAt pgtype.Timestamptz
	ID        string
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, revokeAPIKey, arg.RevokedAt, arg.ID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyHash,
		&i.Mode,
		&i.IsRevoked,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
UPDATE api_keys
SET last_used_at = $1
WHERE id = $2
`

type TouchAPIKeyLastUsedParams struct {
	LastUsedAt pgtype.Timestamptz
	ID         string
}

func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, arg TouchAPIKeyLastUsedParams) error {
	_, err := q.db.Exec(ctx, touchAPIKeyLastUsed, arg.LastUsedAt, arg.ID)
	return err
}
