// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delivery_jobs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelDeliveryJobsForNotification = `-- name: CancelDeliveryJobsForNotification :many
UPDATE delivery_jobs
SET status = 'cancelled',
    locked_at = NULL,
    locked_by = NULL,
    heartbeat_at = NULL,
    updated_at = $1
WHERE notification_id = $2
  AND status IN ('pending', 'retrying')
RETURNING id, notification_id, provider_id, channel, status, payload, send_at, locked_at, locked_by, heartbeat_at, retry_count, max_retries, next_retry_at, last_error, created_at, updated_at, is_test
`

type CancelDeliveryJobsForNotificationParams struct {
	UpdatedAt      pgtype.Timestamptz
	NotificationID string
}

func (q *Queries) CancelDeliveryJobsForNotification(ctx context.Context, arg CancelDeliveryJobsForNotificationParams) ([]DeliveryJob, error) {
	rows, err := q.db.Query(ctx, cancelDeliveryJobsForNotification, arg.UpdatedAt, arg.NotificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryJob
	for rows.Next() {
		var i DeliveryJob
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.ProviderID,
			&i.Channel,
			&i.Status,
			&i.Payload,
			&i.SendAt,
			&i.LockedAt,
			&i.LockedBy,
			&i.HeartbeatAt,
			&i.RetryCount,
			&i.MaxRetries,
			&i.NextRetryAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsTest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createDeliveryJob = `-- name: CreateDeliveryJob :one
INSERT INTO delivery_jobs (
    id,
    notification_id,
    provider_id,
    channel,
    status,
    payload,
    send_at,
    max_retries,
    is_test
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, notification_id, provider_id, channel, status, payload, send_at, locked_at, locked_by, heartbeat_at, retry_count, max_retries, next_retry_at, last_error, created_at, updated_at, is_test
`

type CreateDeliveryJobParams struct {
	ID             string
	NotificationID string
	ProviderID     pgtype.Text
	Channel        string
	Status         string
	Payload        []byte
	SendAt         pgtype.Timestamptz
	MaxRetries     int32
	IsTest         bool
}

func (q *Queries) CreateDeliveryJob(ctx context.Context, arg CreateDeliveryJobParams) (DeliveryJob, error) {
	row := q.db.QueryRow(ctx, createDeliveryJob,
		arg.ID,
		arg.NotificationID,
		arg.ProviderID,
		arg.Channel,
		arg.Status,
		arg.Payload,
		arg.SendAt,
		arg.MaxRetries,
		arg.IsTest,
	)
	var i DeliveryJob
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.ProviderID,
		&i.Channel,
		&i.Status,
		&i.Payload,
		&i.SendAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.HeartbeatAt,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsTest,
	)
	return i, err
}

const getDeliveryJob = `-- name: GetDeliveryJob :one
SELECT id, notification_id, provider_id, channel, status, payload, send_at, locked_at, locked_by, heartbeat_at, retry_count, max_retries, next_retry_at, last_error, created_at, updated_at, is_test
FROM delivery_jobs
WHERE id = $1
`

func (q *Queries) GetDeliveryJob(ctx context.Context, id string) (DeliveryJob, error) {
	row := q.db.QueryRow(ctx, getDeliveryJob, id)
	var i DeliveryJob
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.ProviderID,
		&i.Channel,
		&i.Status,
		&i.Payload,
		&i.SendAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.HeartbeatAt,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsTest,
	)
	return i, err
}

const listDeliveryJobs = `-- name: ListDeliveryJobs :many
SELECT id, notification_id, provider_id, channel, status, payload, send_at, locked_at, locked_by, heartbeat_at, retry_count, max_retries, next_retry_at, last_error, created_at, updated_at, is_test
FROM delivery_jobs
WHERE ($1 = '' OR status = $1)
  AND ($2 = '' OR channel = $2)
  AND ($3 = '' OR notification_id = $3)
  AND send_at >= $4
  AND send_at <= $5
ORDER BY created_at DESC
LIMIT $7
OFFSET $6
`

type ListDeliveryJobsParams struct {
	Status         interface{}
	Channel        interface{}
	NotificationID interface{}
	FromTime       pgtype.Timestamptz
	ToTime         pgtype.Timestamptz
	OffsetCount    int32
	LimitCount     int32
}

func (q *Queries) ListDeliveryJobs(ctx context.Context, arg ListDeliveryJobsParams) ([]DeliveryJob, error) {
	rows, err := q.db.Query(ctx, listDeliveryJobs,
		arg.Status,
		arg.Channel,
		arg.NotificationID,
		arg.FromTime,
		arg.ToTime,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryJob
	for rows.Next() {
		var i DeliveryJob
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.ProviderID,
			&i.Channel,
			&i.Status,
			&i.Payload,
			&i.SendAt,
			&i.LockedAt,
			&i.LockedBy,
			&i.HeartbeatAt,
			&i.RetryCount,
			&i.MaxRetries,
			&i.NextRetryAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsTest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveryJobsByNotificationID = `-- name: ListDeliveryJobsByNotificationID :many
SELECT id, notification_id, provider_id, channel, status, payload, send_at, locked_at, locked_by, heartbeat_at, retry_count, max_retries, next_retry_at, last_error, created_at, updated_at, is_test
FROM delivery_jobs
WHERE notification_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDeliveryJobsByNotificationID(ctx context.Context, notificationID string) ([]DeliveryJob, error) {
	rows, err := q.db.Query(ctx, listDeliveryJobsByNotificationID, notificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryJob
	for rows.Next() {
		var i DeliveryJob
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.ProviderID,
			&i.Channel,
			&i.Status,
			&i.Payload,
			&i.SendAt,
			&i.LockedAt,
			&i.LockedBy,
			&i.HeartbeatAt,
			&i.RetryCount,
			&i.MaxRetries,
			&i.NextRetryAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsTest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockReadyJobs = `-- name: LockReadyJobs :many
WITH ready_jobs AS (
    SELECT id
    FROM delivery_jobs
    WHERE locked_at IS NULL
      AND (
        (status = 'pending' AND send_at <= NOW())
        OR (status = 'retrying' AND next_retry_at IS NOT NULL AND next_retry_at <= NOW())
      )
    ORDER BY send_at ASC, created_at ASC
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
UPDATE delivery_jobs
SET status = 'processing',
    locked_at = NOW(),
    locked_by = $1,
    heartbeat_at = NOW(),
    updated_at = NOW()
WHERE id IN (SELECT id FROM ready_jobs)
RETURNING id, notification_id, provider_id, channel, status, payload, send_at, locked_at, locked_by, heartbeat_at, retry_count, max_retries, next_retry_at, last_error, created_at, updated_at, is_test
`

type LockReadyJobsParams struct {
	WorkerID   pgtype.Text
	LimitCount int32
}

func (q *Queries) LockReadyJobs(ctx context.Context, arg LockReadyJobsParams) ([]DeliveryJob, error) {
	rows, err := q.db.Query(ctx, lockReadyJobs, arg.WorkerID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryJob
	for rows.Next() {
		var i DeliveryJob
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.ProviderID,
			&i.Channel,
			&i.Status,
			&i.Payload,
			&i.SendAt,
			&i.LockedAt,
			&i.LockedBy,
			&i.HeartbeatAt,
			&i.RetryCount,
			&i.MaxRetries,
			&i.NextRetryAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsTest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJobDeadLetter = `-- name: MarkJobDeadLetter :one
UPDATE delivery_jobs
SET status = 'dead_letter',
    last_error = $1,
    locked_at = NULL,
    locked_by = NULL,
    heartbeat_at = NULL,
    updated_at = NOW()
WHERE id = $2
RETURNING id, notification_id, provider_id, channel, status, payload, send_at, locked_at, locked_by, heartbeat_at, retry_count, max_retries, next_retry_at, last_error, created_at, updated_at, is_test
`

type MarkJobDeadLetterParams struct {
	LastError pgtype.Text
	ID        string
}

func (q *Queries) MarkJobDeadLetter(ctx context.Context, arg MarkJobDeadLetterParams) (DeliveryJob, error) {
	row := q.db.QueryRow(ctx, markJobDeadLetter, arg.LastError, arg.ID)
	var i DeliveryJob
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.ProviderID,
		&i.Channel,
		&i.Status,
		&i.Payload,
		&i.SendAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.HeartbeatAt,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsTest,
	)
	return i, err
}

const markJobRetrying = `-- name: MarkJobRetrying :one
UPDATE delivery_jobs
SET status = 'retrying',
    retry_count = retry_count + 1,
    next_retry_at = $1,
    last_error = $2,
    locked_at = NULL,
    locked_by = NULL,
    heartbeat_at = NULL,
    updated_at = NOW()
WHERE id = $3
RETURNING id, notification_id, provider_id, channel, status, payload, send_at, locked_at, locked_by, heartbeat_at, retry_count, max_retries, next_retry_at, last_error, created_at, updated_at, is_test
`

type MarkJobRetryingParams struct {
	NextRetryAt pgtype.Timestamptz
	LastError   pgtype.Text
	ID          string
}

func (q *Queries) MarkJobRetrying(ctx context.Context, arg MarkJobRetryingParams) (DeliveryJob, error) {
	row := q.db.QueryRow(ctx, markJobRetrying, arg.NextRetryAt, arg.LastError, arg.ID)
	var i DeliveryJob
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.ProviderID,
		&i.Channel,
		&i.Status,
		&i.Payload,
		&i.SendAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.HeartbeatAt,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsTest,
	)
	return i, err
}

const markJobSent = `-- name: MarkJobSent :one
UPDATE delivery_jobs
SET status = 'sent',
    locked_at = NULL,
    locked_by = NULL,
    heartbeat_at = NULL,
    last_error = NULL,
    updated_at = NOW()
WHERE id = $1
RETURNING id, notification_id, provider_id, channel, status, payload, send_at, locked_at, locked_by, heartbeat_at, retry_count, max_retries, next_retry_at, last_error, created_at, updated_at, is_test
`

func (q *Queries) MarkJobSent(ctx context.Context, id string) (DeliveryJob, error) {
	row := q.db.QueryRow(ctx, markJobSent, id)
	var i DeliveryJob
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.ProviderID,
		&i.Channel,
		&i.Status,
		&i.Payload,
		&i.SendAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.HeartbeatAt,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsTest,
	)
	return i, err
}

const recoverStaleJobs = `-- name: RecoverStaleJobs :many
UPDATE delivery_jobs
SET status = CASE
        WHEN retry_count > 0 THEN 'retrying'
        ELSE 'pending'
    END,
    locked_at = NULL,
    locked_by = NULL,
    heartbeat_at = NULL,
    updated_at = $1
WHERE locked_at IS NOT NULL
  AND heartbeat_at IS NOT NULL
  AND heartbeat_at < $2
RETURNING id, notification_id, provider_id, channel, status, payload, send_at, locked_at, locked_by, heartbeat_at, retry_count, max_retries, next_retry_at, last_error, created_at, updated_at, is_test
`

type RecoverStaleJobsParams struct {
	UpdatedAt   pgtype.Timestamptz
	StaleBefore pgtype.Timestamptz
}

func (q *Queries) RecoverStaleJobs(ctx context.Context, arg RecoverStaleJobsParams) ([]DeliveryJob, error) {
	rows, err := q.db.Query(ctx, recoverStaleJobs, arg.UpdatedAt, arg.StaleBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryJob
	for rows.Next() {
		var i DeliveryJob
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.ProviderID,
			&i.Channel,
			&i.Status,
			&i.Payload,
			&i.SendAt,
			&i.LockedAt,
			&i.LockedBy,
			&i.HeartbeatAt,
			&i.RetryCount,
			&i.MaxRetries,
			&i.NextRetryAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsTest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rescheduleDeliveryJobsForNotification = `-- name: RescheduleDeliveryJobsForNotification :execrows
UPDATE delivery_jobs
SET send_at = $1,
    updated_at = $2
WHERE notification_id = $3
  AND status IN ('pending', 'retrying')
`

type RescheduleDeliveryJobsForNotificationParams struct {
	SendAt         pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	NotificationID string
}

func (q *Queries) RescheduleDeliveryJobsForNotification(ctx context.Context, arg RescheduleDeliveryJobsForNotificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, rescheduleDeliveryJobsForNotification, arg.SendAt, arg.UpdatedAt, arg.NotificationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDeliveryJobPayloadForNotification = `-- name: UpdateDeliveryJobPayloadForNotification :execrows
UPDATE delivery_jobs
SET payload = $1,
    updated_at = $2
WHERE notification_id = $3
  AND status = 'pending'
`

type UpdateDeliveryJobPayloadForNotificationParams struct {
	Payload        []byte
	UpdatedAt      pgtype.Timestamptz
	NotificationID string
}

func (q *Queries) UpdateDeliveryJobPayloadForNotification(ctx context.Context, arg UpdateDeliveryJobPayloadForNotificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDeliveryJobPayloadForNotification, arg.Payload, arg.UpdatedAt, arg.NotificationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateHeartbeat = `-- name: UpdateHeartbeat :execrows
UPDATE delivery_jobs
SET heartbeat_at = NOW(),
    updated_at = NOW()
WHERE locked_by = $1
  AND locked_at IS NOT NULL
`

func (q *Queries) UpdateHeartbeat(ctx context.Context, workerID pgtype.Text) (int64, error) {
	result, err := q.db.Exec(ctx, updateHeartbeat, workerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
