// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delivery_jobs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelDeliveryJobsForNotification = `-- name: CancelDeliveryJobsForNotification :many
UPDATE delivery_jobs
SET status = 'cancelled',
    locked_at = NULL,
    locked_by = NULL,
    heartbeat_at = NULL,
    updated_at = $1
WHERE notification_id = $2
  AND status IN ('pending', 'retrying')
RETURNING id, notification_id, provider_id, channel, status, payload, send_at, locked_at, locked_by, heartbeat_at, retry_count, max_retries, next_retry_at, last_error, created_at, updated_at
`

type CancelDeliveryJobsForNotificationParams struct {
	UpdatedAt      pgtype.Timestamptz
	NotificationID string
}

func (q *Queries) CancelDeliveryJobsForNotification(ctx context.Context, arg CancelDeliveryJobsForNotificationParams) ([]DeliveryJob, error) {
	rows, err := q.db.Query(ctx, cancelDeliveryJobsForNotification, arg.UpdatedAt, arg.NotificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryJob
	for rows.Next() {
		var i DeliveryJob
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.ProviderID,
			&i.Channel,
			&i.Status,
			&i.Payload,
			&i.SendAt,
			&i.LockedAt,
			&i.LockedBy,
			&i.HeartbeatAt,
			&i.RetryCount,
			&i.MaxRetries,
			&i.NextRetryAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createDeliveryJob = `-- name: CreateDeliveryJob :one
INSERT INTO delivery_jobs (
    id,
    notification_id,
    provider_id,
    channel,
    status,
    payload,
    send_at,
    max_retries
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, notification_id, provider_id, channel, status, payload, send_at, locked_at, locked_by, heartbeat_at, retry_count, max_retries, next_retry_at, last_error, created_at, updated_at
`

type CreateDeliveryJobParams struct {
	ID             string
	NotificationID string
	ProviderID     pgtype.Text
	Channel        string
	Status         string
	Payload        []byte
	SendAt         pgtype.Timestamptz
	MaxRetries     int32
}

func (q *Queries) CreateDeliveryJob(ctx context.Context, arg CreateDeliveryJobParams) (DeliveryJob, error) {
	row := q.db.QueryRow(ctx, createDeliveryJob,
		arg.ID,
		arg.NotificationID,
		arg.ProviderID,
		arg.Channel,
		arg.Status,
		arg.Payload,
		arg.SendAt,
		arg.MaxRetries,
	)
	var i DeliveryJob
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.ProviderID,
		&i.Channel,
		&i.Status,
		&i.Payload,
		&i.SendAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.HeartbeatAt,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeliveryJob = `-- name: GetDeliveryJob :one
SELECT id, notification_id, provider_id, channel, status, payload, send_at, locked_at, locked_by, heartbeat_at, retry_count, max_retries, next_retry_at, last_error, created_at, updated_at
FROM delivery_jobs
WHERE id = $1
`

func (q *Queries) GetDeliveryJob(ctx context.Context, id string) (DeliveryJob, error) {
	row := q.db.QueryRow(ctx, getDeliveryJob, id)
	var i DeliveryJob
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.ProviderID,
		&i.Channel,
		&i.Status,
		&i.Payload,
		&i.SendAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.HeartbeatAt,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDeliveryJobs = `-- name: ListDeliveryJobs :many
SELECT id, notification_id, provider_id, channel, status, payload, send_at, locked_at, locked_by, heartbeat_at, retry_count, max_retries, next_retry_at, last_error, created_at, updated_at
FROM delivery_jobs
WHERE ($1 = '' OR status = $1)
  AND ($2 = '' OR channel = $2)
  AND ($3 = '' OR notification_id = $3)
  AND send_at >= $4
  AND send_at <= $5
ORDER BY created_at DESC
LIMIT $7
OFFSET $6
`

type ListDeliveryJobsParams struct {
	Status         interface{}
	Channel        interface{}
	NotificationID interface{}
	FromTime       pgtype.Timestamptz
	ToTime         pgtype.Timestamptz
	OffsetCount    int32
	LimitCount     int32
}

func (q *Queries) ListDeliveryJobs(ctx context.Context, arg ListDeliveryJobsParams) ([]DeliveryJob, error) {
	rows, err := q.db.Query(ctx, listDeliveryJobs,
		arg.Status,
		arg.Channel,
		arg.NotificationID,
		arg.FromTime,
		arg.ToTime,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryJob
	for rows.Next() {
		var i DeliveryJob
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.ProviderID,
			&i.Channel,
			&i.Status,
			&i.Payload,
			&i.SendAt,
			&i.LockedAt,
			&i.LockedBy,
			&i.HeartbeatAt,
			&i.RetryCount,
			&i.MaxRetries,
			&i.NextRetryAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveryJobsByNotificationID = `-- name: ListDeliveryJobsByNotificationID :many
SELECT id, notification_id, provider_id, channel, status, payload, send_at, locked_at, locked_by, heartbeat_at, retry_count, max_retries, next_retry_at, last_error, created_at, updated_at
FROM delivery_jobs
WHERE notification_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDeliveryJobsByNotificationID(ctx context.Context, notificationID string) ([]DeliveryJob, error) {
	rows, err := q.db.Query(ctx, listDeliveryJobsByNotificationID, notificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryJob
	for rows.Next() {
		var i DeliveryJob
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.ProviderID,
			&i.Channel,
			&i.Status,
			&i.Payload,
			&i.SendAt,
			&i.LockedAt,
			&i.LockedBy,
			&i.HeartbeatAt,
			&i.RetryCount,
			&i.MaxRetries,
			&i.NextRetryAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadyDeliveryJobs = `-- name: ListReadyDeliveryJobs :many
SELECT id, notification_id, provider_id, channel, status, payload, send_at, locked_at, locked_by, heartbeat_at, retry_count, max_retries, next_retry_at, last_error, created_at, updated_at
FROM delivery_jobs
WHERE locked_at IS NULL
  AND (
    (status = 'pending' AND send_at <= $1)
    OR (status = 'retrying' AND next_retry_at IS NOT NULL AND next_retry_at <= $1)
  )
ORDER BY send_at ASC, created_at ASC
LIMIT $2
`

type ListReadyDeliveryJobsParams struct {
	ReadyAt    pgtype.Timestamptz
	LimitCount int32
}

func (q *Queries) ListReadyDeliveryJobs(ctx context.Context, arg ListReadyDeliveryJobsParams) ([]DeliveryJob, error) {
	rows, err := q.db.Query(ctx, listReadyDeliveryJobs, arg.ReadyAt, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryJob
	for rows.Next() {
		var i DeliveryJob
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.ProviderID,
			&i.Channel,
			&i.Status,
			&i.Payload,
			&i.SendAt,
			&i.LockedAt,
			&i.LockedBy,
			&i.HeartbeatAt,
			&i.RetryCount,
			&i.MaxRetries,
			&i.NextRetryAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeliveryJobDeadLetter = `-- name: MarkDeliveryJobDeadLetter :one
UPDATE delivery_jobs
SET status = 'dead_letter',
    last_error = $1,
    locked_at = NULL,
    locked_by = NULL,
    heartbeat_at = NULL,
    updated_at = $2
WHERE id = $3
RETURNING id, notification_id, provider_id, channel, status, payload, send_at, locked_at, locked_by, heartbeat_at, retry_count, max_retries, next_retry_at, last_error, created_at, updated_at
`

type MarkDeliveryJobDeadLetterParams struct {
	LastError pgtype.Text
	UpdatedAt pgtype.Timestamptz
	ID        string
}

func (q *Queries) MarkDeliveryJobDeadLetter(ctx context.Context, arg MarkDeliveryJobDeadLetterParams) (DeliveryJob, error) {
	row := q.db.QueryRow(ctx, markDeliveryJobDeadLetter, arg.LastError, arg.UpdatedAt, arg.ID)
	var i DeliveryJob
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.ProviderID,
		&i.Channel,
		&i.Status,
		&i.Payload,
		&i.SendAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.HeartbeatAt,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markDeliveryJobForRetry = `-- name: MarkDeliveryJobForRetry :one
UPDATE delivery_jobs
SET status = 'retrying',
    retry_count = retry_count + 1,
    next_retry_at = $1,
    last_error = $2,
    locked_at = NULL,
    locked_by = NULL,
    heartbeat_at = NULL,
    updated_at = $3
WHERE id = $4
RETURNING id, notification_id, provider_id, channel, status, payload, send_at, locked_at, locked_by, heartbeat_at, retry_count, max_retries, next_retry_at, last_error, created_at, updated_at
`

type MarkDeliveryJobForRetryParams struct {
	NextRetryAt pgtype.Timestamptz
	LastError   pgtype.Text
	UpdatedAt   pgtype.Timestamptz
	ID          string
}

func (q *Queries) MarkDeliveryJobForRetry(ctx context.Context, arg MarkDeliveryJobForRetryParams) (DeliveryJob, error) {
	row := q.db.QueryRow(ctx, markDeliveryJobForRetry,
		arg.NextRetryAt,
		arg.LastError,
		arg.UpdatedAt,
		arg.ID,
	)
	var i DeliveryJob
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.ProviderID,
		&i.Channel,
		&i.Status,
		&i.Payload,
		&i.SendAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.HeartbeatAt,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markDeliveryJobProcessing = `-- name: MarkDeliveryJobProcessing :one
UPDATE delivery_jobs
SET status = 'processing',
    locked_at = $1,
    locked_by = $2,
    heartbeat_at = $3,
    updated_at = $4
WHERE id = $5
  AND locked_at IS NULL
RETURNING id, notification_id, provider_id, channel, status, payload, send_at, locked_at, locked_by, heartbeat_at, retry_count, max_retries, next_retry_at, last_error, created_at, updated_at
`

type MarkDeliveryJobProcessingParams struct {
	LockedAt    pgtype.Timestamptz
	LockedBy    pgtype.Text
	HeartbeatAt pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	ID          string
}

func (q *Queries) MarkDeliveryJobProcessing(ctx context.Context, arg MarkDeliveryJobProcessingParams) (DeliveryJob, error) {
	row := q.db.QueryRow(ctx, markDeliveryJobProcessing,
		arg.LockedAt,
		arg.LockedBy,
		arg.HeartbeatAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i DeliveryJob
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.ProviderID,
		&i.Channel,
		&i.Status,
		&i.Payload,
		&i.SendAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.HeartbeatAt,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markDeliveryJobSent = `-- name: MarkDeliveryJobSent :one
UPDATE delivery_jobs
SET status = 'sent',
    locked_at = NULL,
    locked_by = NULL,
    heartbeat_at = NULL,
    last_error = NULL,
    updated_at = $1
WHERE id = $2
RETURNING id, notification_id, provider_id, channel, status, payload, send_at, locked_at, locked_by, heartbeat_at, retry_count, max_retries, next_retry_at, last_error, created_at, updated_at
`

type MarkDeliveryJobSentParams struct {
	UpdatedAt pgtype.Timestamptz
	ID        string
}

func (q *Queries) MarkDeliveryJobSent(ctx context.Context, arg MarkDeliveryJobSentParams) (DeliveryJob, error) {
	row := q.db.QueryRow(ctx, markDeliveryJobSent, arg.UpdatedAt, arg.ID)
	var i DeliveryJob
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.ProviderID,
		&i.Channel,
		&i.Status,
		&i.Payload,
		&i.SendAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.HeartbeatAt,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const rescheduleDeliveryJobsForNotification = `-- name: RescheduleDeliveryJobsForNotification :execrows
UPDATE delivery_jobs
SET send_at = $1,
    updated_at = $2
WHERE notification_id = $3
  AND status IN ('pending', 'retrying')
`

type RescheduleDeliveryJobsForNotificationParams struct {
	SendAt         pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	NotificationID string
}

func (q *Queries) RescheduleDeliveryJobsForNotification(ctx context.Context, arg RescheduleDeliveryJobsForNotificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, rescheduleDeliveryJobsForNotification, arg.SendAt, arg.UpdatedAt, arg.NotificationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetStaleDeliveryJobs = `-- name: ResetStaleDeliveryJobs :many
UPDATE delivery_jobs
SET status = CASE
        WHEN retry_count > 0 THEN 'retrying'
        ELSE 'pending'
    END,
    locked_at = NULL,
    locked_by = NULL,
    heartbeat_at = NULL,
    updated_at = $1
WHERE locked_at IS NOT NULL
  AND heartbeat_at IS NOT NULL
  AND heartbeat_at < $2
RETURNING id, notification_id, provider_id, channel, status, payload, send_at, locked_at, locked_by, heartbeat_at, retry_count, max_retries, next_retry_at, last_error, created_at, updated_at
`

type ResetStaleDeliveryJobsParams struct {
	UpdatedAt   pgtype.Timestamptz
	StaleBefore pgtype.Timestamptz
}

func (q *Queries) ResetStaleDeliveryJobs(ctx context.Context, arg ResetStaleDeliveryJobsParams) ([]DeliveryJob, error) {
	rows, err := q.db.Query(ctx, resetStaleDeliveryJobs, arg.UpdatedAt, arg.StaleBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryJob
	for rows.Next() {
		var i DeliveryJob
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.ProviderID,
			&i.Channel,
			&i.Status,
			&i.Payload,
			&i.SendAt,
			&i.LockedAt,
			&i.LockedBy,
			&i.HeartbeatAt,
			&i.RetryCount,
			&i.MaxRetries,
			&i.NextRetryAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeliveryJobPayloadForNotification = `-- name: UpdateDeliveryJobPayloadForNotification :execrows
UPDATE delivery_jobs
SET payload = $1,
    updated_at = $2
WHERE notification_id = $3
  AND status = 'pending'
`

type UpdateDeliveryJobPayloadForNotificationParams struct {
	Payload        []byte
	UpdatedAt      pgtype.Timestamptz
	NotificationID string
}

func (q *Queries) UpdateDeliveryJobPayloadForNotification(ctx context.Context, arg UpdateDeliveryJobPayloadForNotificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDeliveryJobPayloadForNotification, arg.Payload, arg.UpdatedAt, arg.NotificationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateHeartbeatForWorker = `-- name: UpdateHeartbeatForWorker :many
UPDATE delivery_jobs
SET heartbeat_at = $1,
    updated_at = $2
WHERE locked_by = $3
  AND status = 'processing'
RETURNING id, notification_id, provider_id, channel, status, payload, send_at, locked_at, locked_by, heartbeat_at, retry_count, max_retries, next_retry_at, last_error, created_at, updated_at
`

type UpdateHeartbeatForWorkerParams struct {
	HeartbeatAt pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	LockedBy    pgtype.Text
}

func (q *Queries) UpdateHeartbeatForWorker(ctx context.Context, arg UpdateHeartbeatForWorkerParams) ([]DeliveryJob, error) {
	rows, err := q.db.Query(ctx, updateHeartbeatForWorker, arg.HeartbeatAt, arg.UpdatedAt, arg.LockedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryJob
	for rows.Next() {
		var i DeliveryJob
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.ProviderID,
			&i.Channel,
			&i.Status,
			&i.Payload,
			&i.SendAt,
			&i.LockedAt,
			&i.LockedBy,
			&i.HeartbeatAt,
			&i.RetryCount,
			&i.MaxRetries,
			&i.NextRetryAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
