// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delivery_attempts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeliveryAttempt = `-- name: CreateDeliveryAttempt :one
INSERT INTO delivery_attempts (
    id,
    delivery_job_id,
    attempt_number,
    provider_name,
    status,
    request_payload,
    response_payload,
    error_message,
    duration_ms,
    attempted_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, delivery_job_id, attempt_number, provider_name, status, request_payload, response_payload, error_message, duration_ms, attempted_at
`

type CreateDeliveryAttemptParams struct {
	ID              string
	DeliveryJobID   string
	AttemptNumber   int32
	ProviderName    string
	Status          string
	RequestPayload  []byte
	ResponsePayload []byte
	ErrorMessage    pgtype.Text
	DurationMs      pgtype.Int4
	AttemptedAt     pgtype.Timestamptz
}

func (q *Queries) CreateDeliveryAttempt(ctx context.Context, arg CreateDeliveryAttemptParams) (DeliveryAttempt, error) {
	row := q.db.QueryRow(ctx, createDeliveryAttempt,
		arg.ID,
		arg.DeliveryJobID,
		arg.AttemptNumber,
		arg.ProviderName,
		arg.Status,
		arg.RequestPayload,
		arg.ResponsePayload,
		arg.ErrorMessage,
		arg.DurationMs,
		arg.AttemptedAt,
	)
	var i DeliveryAttempt
	err := row.Scan(
		&i.ID,
		&i.DeliveryJobID,
		&i.AttemptNumber,
		&i.ProviderName,
		&i.Status,
		&i.RequestPayload,
		&i.ResponsePayload,
		&i.ErrorMessage,
		&i.DurationMs,
		&i.AttemptedAt,
	)
	return i, err
}

const listDeliveryAttemptsByJob = `-- name: ListDeliveryAttemptsByJob :many
SELECT id, delivery_job_id, attempt_number, provider_name, status, request_payload, response_payload, error_message, duration_ms, attempted_at
FROM delivery_attempts
WHERE delivery_job_id = $1
ORDER BY attempt_number ASC
`

func (q *Queries) ListDeliveryAttemptsByJob(ctx context.Context, deliveryJobID string) ([]DeliveryAttempt, error) {
	rows, err := q.db.Query(ctx, listDeliveryAttemptsByJob, deliveryJobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryAttempt
	for rows.Next() {
		var i DeliveryAttempt
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryJobID,
			&i.AttemptNumber,
			&i.ProviderName,
			&i.Status,
			&i.RequestPayload,
			&i.ResponsePayload,
			&i.ErrorMessage,
			&i.DurationMs,
			&i.AttemptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
