// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         string
	Name       string
	KeyHash    string
	Mode       string
	IsRevoked  bool
	LastUsedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

type DeliveryAttempt struct {
	ID              string
	DeliveryJobID   string
	AttemptNumber   int32
	ProviderName    string
	Status          string
	RequestPayload  []byte
	ResponsePayload []byte
	ErrorMessage    pgtype.Text
	DurationMs      pgtype.Int4
	AttemptedAt     pgtype.Timestamptz
}

type DeliveryJob struct {
	ID             string
	NotificationID string
	ProviderID     pgtype.Text
	Channel        string
	Status         string
	Payload        []byte
	SendAt         pgtype.Timestamptz
	LockedAt       pgtype.Timestamptz
	LockedBy       pgtype.Text
	HeartbeatAt    pgtype.Timestamptz
	RetryCount     int32
	MaxRetries     int32
	NextRetryAt    pgtype.Timestamptz
	LastError      pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Notification struct {
	ID             string
	IdempotencyKey string
	Status         string
	Tag            string
	Content        []byte
	Metadata       []byte
	SendAt         pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	CancelledAt    pgtype.Timestamptz
}

type Provider struct {
	ID        string
	Name      string
	Channel   string
	Config    []byte
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
