// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelNotification = `-- name: CancelNotification :one
UPDATE notifications
SET status = 'cancelled',
    cancelled_at = $1,
    updated_at = $2
WHERE id = $3
RETURNING id, idempotency_key, status, tag, content, metadata, send_at, created_at, updated_at, cancelled_at
`

type CancelNotificationParams struct {
	CancelledAt pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	ID          string
}

func (q *Queries) CancelNotification(ctx context.Context, arg CancelNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, cancelNotification, arg.CancelledAt, arg.UpdatedAt, arg.ID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Status,
		&i.Tag,
		&i.Content,
		&i.Metadata,
		&i.SendAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    id,
    idempotency_key,
    status,
    tag,
    content,
    metadata,
    send_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, idempotency_key, status, tag, content, metadata, send_at, created_at, updated_at, cancelled_at
`

type CreateNotificationParams struct {
	ID             string
	IdempotencyKey string
	Status         string
	Tag            string
	Content        []byte
	Metadata       []byte
	SendAt         pgtype.Timestamptz
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.ID,
		arg.IdempotencyKey,
		arg.Status,
		arg.Tag,
		arg.Content,
		arg.Metadata,
		arg.SendAt,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Status,
		&i.Tag,
		&i.Content,
		&i.Metadata,
		&i.SendAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const getNotification = `-- name: GetNotification :one
SELECT id, idempotency_key, status, tag, content, metadata, send_at, created_at, updated_at, cancelled_at
FROM notifications
WHERE id = $1
`

func (q *Queries) GetNotification(ctx context.Context, id string) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotification, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Status,
		&i.Tag,
		&i.Content,
		&i.Metadata,
		&i.SendAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const getNotificationByIdempotencyKey = `-- name: GetNotificationByIdempotencyKey :one
SELECT id, idempotency_key, status, tag, content, metadata, send_at, created_at, updated_at, cancelled_at
FROM notifications
WHERE idempotency_key = $1
`

func (q *Queries) GetNotificationByIdempotencyKey(ctx context.Context, idempotencyKey string) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByIdempotencyKey, idempotencyKey)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Status,
		&i.Tag,
		&i.Content,
		&i.Metadata,
		&i.SendAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, idempotency_key, status, tag, content, metadata, send_at, created_at, updated_at, cancelled_at
FROM notifications
WHERE ($1 = '' OR status = $1)
  AND ($2 = '' OR tag = $2)
  AND send_at >= $3
  AND send_at <= $4
ORDER BY created_at DESC
LIMIT $6
OFFSET $5
`

type ListNotificationsParams struct {
	Status      interface{}
	Tag         interface{}
	FromTime    pgtype.Timestamptz
	ToTime      pgtype.Timestamptz
	OffsetCount int32
	LimitCount  int32
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.Status,
		arg.Tag,
		arg.FromTime,
		arg.ToTime,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.IdempotencyKey,
			&i.Status,
			&i.Tag,
			&i.Content,
			&i.Metadata,
			&i.SendAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rescheduleNotification = `-- name: RescheduleNotification :one
UPDATE notifications
SET send_at = $1,
    updated_at = $2
WHERE id = $3
RETURNING id, idempotency_key, status, tag, content, metadata, send_at, created_at, updated_at, cancelled_at
`

type RescheduleNotificationParams struct {
	SendAt    pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	ID        string
}

func (q *Queries) RescheduleNotification(ctx context.Context, arg RescheduleNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, rescheduleNotification, arg.SendAt, arg.UpdatedAt, arg.ID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Status,
		&i.Tag,
		&i.Content,
		&i.Metadata,
		&i.SendAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const updateNotificationContent = `-- name: UpdateNotificationContent :one
UPDATE notifications
SET content = $1,
    metadata = $2,
    updated_at = $3
WHERE id = $4
RETURNING id, idempotency_key, status, tag, content, metadata, send_at, created_at, updated_at, cancelled_at
`

type UpdateNotificationContentParams struct {
	Content   []byte
	Metadata  []byte
	UpdatedAt pgtype.Timestamptz
	ID        string
}

func (q *Queries) UpdateNotificationContent(ctx context.Context, arg UpdateNotificationContentParams) (Notification, error) {
	row := q.db.QueryRow(ctx, updateNotificationContent,
		arg.Content,
		arg.Metadata,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Status,
		&i.Tag,
		&i.Content,
		&i.Metadata,
		&i.SendAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const updateNotificationStatus = `-- name: UpdateNotificationStatus :one
UPDATE notifications
SET status = $1,
    updated_at = $2
WHERE id = $3
RETURNING id, idempotency_key, status, tag, content, metadata, send_at, created_at, updated_at, cancelled_at
`

type UpdateNotificationStatusParams struct {
	Status    string
	UpdatedAt pgtype.Timestamptz
	ID        string
}

func (q *Queries) UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) (Notification, error) {
	row := q.db.QueryRow(ctx, updateNotificationStatus, arg.Status, arg.UpdatedAt, arg.ID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Status,
		&i.Tag,
		&i.Content,
		&i.Metadata,
		&i.SendAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}
