// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: providers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProvider = `-- name: CreateProvider :one
INSERT INTO providers (
    id,
    name,
    channel,
    config,
    is_active
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, name, channel, config, is_active, created_at, updated_at
`

type CreateProviderParams struct {
	ID       string
	Name     string
	Channel  string
	Config   []byte
	IsActive bool
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.ID,
		arg.Name,
		arg.Channel,
		arg.Config,
		arg.IsActive,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Channel,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProvider = `-- name: GetProvider :one
SELECT id, name, channel, config, is_active, created_at, updated_at
FROM providers
WHERE id = $1
`

func (q *Queries) GetProvider(ctx context.Context, id string) (Provider, error) {
	row := q.db.QueryRow(ctx, getProvider, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Channel,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProvidersByChannel = `-- name: ListProvidersByChannel :many
SELECT id, name, channel, config, is_active, created_at, updated_at
FROM providers
WHERE channel = $1
  AND is_active = TRUE
ORDER BY name ASC
`

func (q *Queries) ListProvidersByChannel(ctx context.Context, channel string) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProvidersByChannel, channel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Provider
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Channel,
			&i.Config,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProviderConfig = `-- name: UpdateProviderConfig :one
UPDATE providers
SET config = $1,
    is_active = $2,
    updated_at = $3
WHERE id = $4
RETURNING id, name, channel, config, is_active, created_at, updated_at
`

type UpdateProviderConfigParams struct {
	Config    []byte
	IsActive  bool
	UpdatedAt pgtype.Timestamptz
	ID        string
}

func (q *Queries) UpdateProviderConfig(ctx context.Context, arg UpdateProviderConfigParams) (Provider, error) {
	row := q.db.QueryRow(ctx, updateProviderConfig,
		arg.Config,
		arg.IsActive,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Channel,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
